Homework1
made-ml-in-prod-2021/reconrus pull request #2
Opened 2021-05-09 20:59 UTC by reconrus

2021-05-10 08:46 UTC, SokoloiD requested changes
Все супер! Есть небольшие замечания по использованию гидры.

2021-05-10 08:46 UTC, SokoloiD commented on ml_project/ml_project/.hydra/config.yaml
> +feature_params:
feature_params: стоит вынести в отдельный yaml файл

2021-05-10 08:46 UTC, SokoloiD commented on .hydra/config.yaml
> +feature_parameters:
feature_params:  стоит вынести в отдельный yaml файл

2021-05-10 08:46 UTC, SokoloiD commented on ml_project/ml_project/configs/predict_config.yaml
> +feature_parameters:
feature_params:  стоит вынести в отдельный yaml файл

2021-05-10 08:46 UTC, SokoloiD commented on ml_project/ml_project/configs/train_config.yaml
> +feature_params:
feature_params:  стоит вынести в отдельный yaml файл

2021-05-10 08:46 UTC, SokoloiD commented on ml_project/ml_project/visualization/generate_profiling_report.py
> +def setup_parser():
В проекте уже применяется hydra . Использование  argparse выглядит избыточным. Рекомендую использовать для передачи аргументов функционал гидру

2021-05-11 09:23 UTC, Danil328 approved these changes
Работа выполнена качественно
28 баллов

2021-05-11 09:23 UTC, Danil328 commented on ml_project/ml_project/data/process_data.py
> +from ml_project.utils.read_files import read_csv
Тут лучше относительный импорт использовать, так как внутри пакета

2021-05-11 09:23 UTC, Danil328 commented on ml_project/ml_project/entities/training_params.py
> +from ml_project.entities.feature_params import FeatureParams
Тут тоже

2021-05-11 09:23 UTC, Danil328 commented on ml_project/ml_project/features/build_features.py
> +    def fit(self, X, y=None):
Тип для x и y

2021-05-11 09:23 UTC, Danil328 commented on ml_project/ml_project/models/predict.py
> +from ml_project.utils.read_files import read_csv
Относительный импорт

2021-05-11 09:23 UTC, Danil328 commented on ml_project/ml_project/predict_pipeline.py
> +from ml_project.data.process_data import process_data
Относительный импорт

2021-05-11 09:23 UTC, Danil328 commented on ml_project/ml_project/train_pipeline.py
> +from ml_project.data.process_data import process_data, split_data, split_features_and_target
Относительный импорт

2021-06-21 20:55 UTC, merged